server:
  port: 8080

spring:
  application:
    name: springboot-backend-base
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

